language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

# faster builds on new travis setup not using sudo
sudo: false

before_install:
  - pecl channel-update pecl.php.net
  - yes "" | pecl -q install -f apcu

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --dev --prefer-dist --no-interaction

script:
  - composer validate --strict
  # This module has no tests yet
  - php -l src/Codeception/Module/Apc.php
